"use client";
import { useRouter } from "next/navigation";
import useAdminUser from "../../utils/use-admin-user";
import { useEffect } from "react";
import { ProgressSpinner } from "primereact/progressspinner";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();
  const { data, isLoading } = useAdminUser();

  useEffect(() => {
    if (data && !isLoading) {
      router.push("/");
    }
  }, [data, router.push]);

  if (!isLoading) {
    return (
      <div className="layout-wrapper">
        <div className="layout-main-container">{children}</div>
      </div>
    );
  }
  return (
    <div className="h-screen flex align-items-center  ">
      <ProgressSpinner className="flex align-items-center" />
    </div>
  );
}
